spring.application.name=msrappel

logging.level.org.springframework=INFO
server.port=8094

spring.profiles.active=prod
#spring.config.import=optional:configserver:http://docker.internal:8071/
spring.config.import=optional:configserver:http://localhost:8071/

cloud.consul.host=localhost
cloud.consul.port=8500
cloud.consul.discovery.enabled=true
cloud.consul.discovery.health-check-interval=15s